apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: us-central1-docker.pkg.dev/encoded-metrics-401109/my-repository/flask:1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: flask
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer